language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
env:
  - YTDL_TEST_SET=core
  - YTDL_TEST_SET=download
matrix:
  fast_finish: true
  allow_failures:
    - env: YTDL_TEST_SET=download
script: ./devscripts/run_tests.sh
notifications:
  email:
    - filippo.valsorda@gmail.com
    - yasoob.khld@gmail.com
